version: '3.9'

services:
  # MariaDB数据库
  db:
    image: mariadb:10.6
    container_name: datascope-mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: datascope
      MYSQL_DATABASE: datascope
      MYSQL_USER: datascope
      MYSQL_PASSWORD: datascope
      MARIADB_ROOT_HOST: '%'
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pdatascope"]
      interval: 30s
      timeout: 10s
      retries: 5
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --bind-address=0.0.0.0 --skip-networking=0

  # DataScope前端
  frontend:
    image: node:18-alpine
    container_name: datascope-frontend
    depends_on:
      - db
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    command: >
      sh -c "cd webview-ui && 
             npm install && 
             npm run dev -- --host 0.0.0.0"
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 5

  # DataScope后端
  backend:
    image: node:18-alpine
    container_name: datascope-backend
    depends_on:
      - db
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mysql://root:datascope@db:3306/datascope
      - PORT=5000
      - ENCRYPTION_KEY=datascope-default-encryption-key-12345
    command: >
      sh -c "cd webService && 
             npm install && 
             npx prisma generate && 
             npm run start:dev"
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  mariadb_data: