version: '3.8'

services:
  # MySQL 测试数据库
  datascope-mysql:
    image: mysql:8
    container_name: datascope-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: datascope
      MYSQL_DATABASE: datascope
      MYSQL_USER: datauser
      MYSQL_PASSWORD: datapass
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pdatascope"]
      interval: 10s
      timeout: 5s
      retries: 5

  # PostgreSQL 测试数据库
  datascope-postgres:
    image: postgres:14
    container_name: datascope-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # MariaDB 作为另一个测试实例
  datascope-mariadb:
    image: mariadb:10.6
    container_name: datascope-mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: datapass
      MARIADB_DATABASE: example_db
      MARIADB_USER: datauser
      MARIADB_PASSWORD: datapass
    ports:
      - "3307:3306"
    volumes:
      - ./docker/mariadb/init:/docker-entrypoint-initdb.d
      - mariadb-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pdatapass"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql-data:
  postgres-data:
  mariadb-data: 